# Generated by Django 5.1.6 on 2025-03-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-order_date',), 'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
    ]
